name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Test
      run: make test
    - name: Install Packaging dependencies
      run: sudo apt-get -qq --no-install-recommends install debhelper devscripts lintian fakeroot
    - name: Package
      run: debuild -us -uc
