name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Test
      run: make test
  deb:
    name: Debian Packaging
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Dump Github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get -qq --no-install-recommends install debhelper devscripts lintian fakeroot
    - name: Build package
      run: |
        debuild -us -uc
        mkdir ./debs
        cp ../*.deb ./debs
    - name: Upload package as artifact
      uses: actions/upload-artifact@v1
      with:
        name: debs
        path: ./debs/
    - name: Upload package to aptly
      # if: github.event_name == 'pull_request' ....
      uses: ./.github/actions/aptly-upload-action
      with:
        path: ./debs/
        api_url: ${{ secrets.APTLY_URL }}
        api_auth: ${{ secrets.APTLY_AUTH }}
